version: "3.8"
services:
  php-apache-environment:
    build:
      context: ./src
    container_name: php-apache
    volumes:
      - ./web/src:/var/www/html
    ports:
      - "8088:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_opinno
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9906:3306"

volumes:
  db_data:
